### ISSUE TITLE
How can MainActivity be used instead of Java?

### ISSUE THREAD

**Issue by fail572872916** [c004245/AndroidThingsCamera#1]
![tim 20181024143117](https://user-images.githubusercontent.com/19763500/47410802-83712a80-d799-11e8-9b13-c4b74e3d3f6d.png)

**Comment by c004245** [comment]
Hi, I don't understand your question.     you need `Main3Activity` name?

**Comment by c004245** [comment]
Hello,    you want my MainActivity.kt (Kotlin) -> your MainActivity.java (java) right?

**Comment by c004245** [comment]
`texture.surfaceTextureListener = textureListener`.  --> `texture.setSurfaceTextureListener(this.textureListener);`

**Comment by fail572872916** [comment]
However, after I switched to Java MainActivity, I could not call the camera and preview it. What's going on here?

**Comment by fail572872916** [comment]
However, after I switched to Java MainActivity, I could not call the camera and preview it. What's going on here?

**Comment by c004245** [comment]
I should check your MainActivity.java

**Comment by fail572872916** [comment]
I think I made a mistake.  Since I'm not familiar with Kotlin, there's an error in looking at your code and then converting it to Java code, which is now resolved

The error is as follows ：
you kotlin code
`  private var mBackgroundHandler : Handler? = null`
my chcahnge
`  private Handler mBackgroundHandler =null;`
Correct code
`    private Handler mBackgroundHandler = new Handler();`

-----Thank you for your code

**Comment by c004245** [comment]
I am glad you solved it. Thanks you 🙌
